name: Deploy Static Site Using Azure Storage, Azure CDN and Terraform

on:
  push:
    branches:
      - main

env:
  TF_CLOUD_ORGANIZATION: azure-terraform-labs
  TF_WORKSPACE: azure-cloud-resume-challenge-prod
  TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 'v1.12.2'
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Upload static site files to Azure Storage
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az storage blob upload-batch \
              --account-name stcrc002 \
              --destination '$web' \
              --source ./site \
              --auth-mode login \
              --overwrite

      - name: Purge CDN endpoint
        run: az cdn endpoint purge -g rg-crc-prod-001 -n ep-crc-prod-001 --profile-name cdn-crc-prod-001 --content-paths "/*"
